dist: trusty
sudo: required
language: cpp
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq nettle-dev
#- sudo apt-get install -qq nbdkit-plugin-dev
# Not in any of the ancient platforms Travis offers

script:
- autoreconf -is
- ./configure
- make check
