os:
- linux
- osx

dist: xenial
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - nettle-dev
    - libjsoncpp-dev
    - nbdkit-plugin-dev
language: cpp
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" && ! -d /usr/local/Cellar/nettle ]]; then brew install nettle; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tinyxml; fi

script:
- autoreconf -is
- ./configure
- make check
