#! /bin/sh
#
# This file is part of vbig.
# Copyright (C) 2014, 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e

rm -f testfile.$$

if ${VBIG:-./vbig} --rng arcfour --create "$@" testfile.$$ 65536; then
    echo >&2 "ERROR: --create with arcfour didn't fail"
    exit 1
fi

if [ -e testfile.$$ ]; then
    echo >&2 "ERROR: --create with arcfour still created output"
    exit 1
fi

if ${VBIG:-./vbig} --rng arcfour --both "$@" testfile.$$ 65536; then
    echo >&2 "ERROR: --both with arcfour didn't fail"
    exit 1
fi

if [ -e testfile.$$ ]; then
    echo >&2 "ERROR: --both with arcfour still created output"
    exit 1
fi
