#! /bin/sh
set -e
rm -f testfile
./vbig --seed chahthaiquiyouto --create testfile 65536
dd if=/dev/zero of=testfile bs=256 count=1 seek=1 conv=nocreat,notrunc oflag=append status=noxfer
if ./vbig --seed chahthaiquiyouto --verify testfile 65536 2>testoutput; then
  echo >&2 ERROR: verify unexpectedly succeeded
  exit 1
fi
echo 'ERROR: testfile: extended beyond 65536 bytes' > testexpect
diff -u testexpect testoutput
rm -f testfile testoutput testexpect
