#! /bin/sh
#
# This file is part of vbig.
# Copyright (C) 2016 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e

nbd="$1"
nbd=${nbd##*:}

for candidate in /sys/class/block/nbd*; do
    read size < "$candidate/size"
    if [ "$size" = 0 ]; then
        dev=/dev/"${candidate##*/}"
        break
    fi
done

if [ "${dev}" = "" ]; then
    echo >&2 "ERROR: no spare nbd found"
    exit 77
fi

nbd-client -unix $nbd ${dev}
trap "nbd-client -d ${dev}" EXIT INT HUP TERM

if ./vbig --flush ${dev}; then
    echo >&2 "ERROR: vbig did not detect bogus device"
    exit 1
fi
