#! /bin/sh
#
# This file is part of vbig.
# Copyright (C) 2014, 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e

check() {
  rm -f testfile.$$
  ${VBIG:-./vbig} --seed chahthaiquiyouto --create "$@" testfile.$$ 65536
  dd if=/dev/null of=testfile.$$ bs=32768 seek=1
  if ${VBIG:-./vbig} --seed chahthaiquiyouto --verify "$@" testfile.$$ 65536 2>testoutput.$$; then
    echo >&2 ERROR: verify unexpectedly succeeded
    exit 1
  fi
  rm -f testexpect.$$
  if [ "$2" = "arcfour" ]; then
    echo 'WARNING: arcfour algorithm is insecure' > testexpect.$$
  fi
  echo "ERROR: testfile.$$: truncated at 32768/65536 bytes" >> testexpect.$$
  diff -u testexpect.$$ testoutput.$$
  rm -f testfile.$$ testoutput.$$ testexpect.$$
}

check
check --rng arcfour-drop-3072
check --rng aes-ctr-drbg-128
check --rng aes-ctr-drbg-192
check --rng aes-ctr-drbg-256
